# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jpmobile}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoji Shidara", "Shin-ichiro OGAWA"]
  s.date = %q{2010-08-31}
  s.description = %q{A Rails plugin for Japanese mobile-phones}
  s.email = %q{dara@shidara.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "init.rb",
     "install.rb",
     "jpmobile.gemspec",
     "lib/jpmobile.rb",
     "lib/jpmobile/datum_conv.rb",
     "lib/jpmobile/docomo_guid.rb",
     "lib/jpmobile/email.rb",
     "lib/jpmobile/emoticon.rb",
     "lib/jpmobile/emoticon/au.rb",
     "lib/jpmobile/emoticon/conversion_table.rb",
     "lib/jpmobile/emoticon/docomo.rb",
     "lib/jpmobile/emoticon/softbank.rb",
     "lib/jpmobile/emoticon/z_combine.rb",
     "lib/jpmobile/filter.rb",
     "lib/jpmobile/helpers.rb",
     "lib/jpmobile/hook_action_controller.rb",
     "lib/jpmobile/hook_action_view.rb",
     "lib/jpmobile/hook_request.rb",
     "lib/jpmobile/mobile/abstract_mobile.rb",
     "lib/jpmobile/mobile/au.rb",
     "lib/jpmobile/mobile/display.rb",
     "lib/jpmobile/mobile/docomo.rb",
     "lib/jpmobile/mobile/emobile.rb",
     "lib/jpmobile/mobile/softbank.rb",
     "lib/jpmobile/mobile/willcom.rb",
     "lib/jpmobile/mobile/z_display_info_docomo.rb",
     "lib/jpmobile/mobile/z_ip_addresses_au.rb",
     "lib/jpmobile/mobile/z_ip_addresses_docomo.rb",
     "lib/jpmobile/mobile/z_ip_addresses_emobile.rb",
     "lib/jpmobile/mobile/z_ip_addresses_softbank.rb",
     "lib/jpmobile/mobile/z_ip_addresses_willcom.rb",
     "lib/jpmobile/position.rb",
     "lib/jpmobile/rack/auth.rb",
     "lib/jpmobile/rack/combined_logger.rb",
     "lib/jpmobile/rack/request.rb",
     "lib/jpmobile/rack/trans_sid.rb",
     "lib/jpmobile/request_with_mobile.rb",
     "lib/jpmobile/trans_sid.rb",
     "lib/jpmobile/util.rb",
     "lib/jpmobile/version.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/unit/detect_by_email_spec.rb",
     "spec/unit/detect_by_ua_spec.rb",
     "spec/unit/is_carrier_spec.rb",
     "spec/unit/spec_helper.rb",
     "spec/unit/util_spec.rb",
     "spec/unit/valid_ip_spec.rb",
     "tasks/jpmobile_tasks.rake",
     "test/legacy/au_test.rb",
     "test/legacy/autoload_test.rb",
     "test/legacy/docomo_test.rb",
     "test/legacy/emoticon_functional_test.rb",
     "test/legacy/emoticon_test.rb",
     "test/legacy/filter_test.rb",
     "test/legacy/helper.rb",
     "test/legacy/helpers_test.rb",
     "test/legacy/softbank_test.rb",
     "test/legacy/willcom_test.rb",
     "test/rails/.gitignore",
     "test/rails/2.3.2/spec/controllers/trans_sid_spec.rb",
     "test/rails/overrides/app/controllers/application_controller.rb",
     "test/rails/overrides/app/controllers/docomo_guid_controller.rb",
     "test/rails/overrides/app/controllers/filter_controller.rb",
     "test/rails/overrides/app/controllers/mobile_spec_controller.rb",
     "test/rails/overrides/app/controllers/template_path_controller.rb",
     "test/rails/overrides/app/controllers/trans_sid_controller.rb",
     "test/rails/overrides/app/views/filter/index.html.erb",
     "test/rails/overrides/app/views/hankaku_filter/index.html.erb",
     "test/rails/overrides/app/views/template_path/_partial.html.erb",
     "test/rails/overrides/app/views/template_path/_partial_mobile.html.erb",
     "test/rails/overrides/app/views/template_path/_partial_mobile_docomo.html.erb",
     "test/rails/overrides/app/views/template_path/index.html.erb",
     "test/rails/overrides/app/views/template_path/index_mobile.html.erb",
     "test/rails/overrides/app/views/template_path/index_mobile_docomo.html.erb",
     "test/rails/overrides/app/views/template_path/partial.html.erb",
     "test/rails/overrides/lib/tasks/rspec.rake",
     "test/rails/overrides/spec/controllers/docomo_guid_spec.rb",
     "test/rails/overrides/spec/controllers/docomo_spec.rb",
     "test/rails/overrides/spec/controllers/emobile_spec.rb",
     "test/rails/overrides/spec/controllers/filter_spec.rb",
     "test/rails/overrides/spec/controllers/pc_spec.rb",
     "test/rails/overrides/spec/controllers/softbank_emulator_spec.rb",
     "test/rails/overrides/spec/controllers/template_path_spec.rb",
     "test/rails/overrides/spec/controllers/trans_sid_spec.rb",
     "test/rails/overrides/spec/helpers/helpers_spec.rb",
     "test/rails/overrides/spec/rcov.opts",
     "test/rails/overrides/spec/rspec.rake",
     "test/rails/overrides/spec/spec.opts",
     "test/rails/overrides/spec/spec_helper.rb",
     "tools/disabled_update_display_info_docomo.rb",
     "tools/emoji/genregexp.rb",
     "tools/generate_au_emoticon_table.rb",
     "tools/generate_docomo_emoticon_table.rb",
     "tools/generate_emoticon_conversion_table.rb",
     "tools/generate_softbank_emoticon_table.rb",
     "tools/list_gps_unsupported_au.rb",
     "tools/update_ip_addresses_au.rb",
     "tools/update_ip_addresses_willcom.rb"
  ]
  s.homepage = %q{http://github.com/jpmobile/jpmobile}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rails plugin for Japanese mobile-phones}
  s.test_files = [
    "spec/unit/detect_by_email_spec.rb",
     "spec/unit/detect_by_ua_spec.rb",
     "spec/unit/spec_helper.rb",
     "spec/unit/valid_ip_spec.rb",
     "spec/unit/util_spec.rb",
     "spec/unit/is_carrier_spec.rb",
     "spec/spec_helper.rb",
     "test/legacy/filter_test.rb",
     "test/legacy/autoload_test.rb",
     "test/legacy/softbank_test.rb",
     "test/legacy/au_test.rb",
     "test/legacy/willcom_test.rb",
     "test/legacy/emoticon_functional_test.rb",
     "test/legacy/emoticon_test.rb",
     "test/legacy/helpers_test.rb",
     "test/legacy/docomo_test.rb",
     "test/legacy/helper.rb",
     "test/rails/overrides/spec/helpers/helpers_spec.rb",
     "test/rails/overrides/spec/spec_helper.rb",
     "test/rails/overrides/spec/controllers/softbank_emulator_spec.rb",
     "test/rails/overrides/spec/controllers/docomo_spec.rb",
     "test/rails/overrides/spec/controllers/docomo_guid_spec.rb",
     "test/rails/overrides/spec/controllers/trans_sid_spec.rb",
     "test/rails/overrides/spec/controllers/template_path_spec.rb",
     "test/rails/overrides/spec/controllers/filter_spec.rb",
     "test/rails/overrides/spec/controllers/pc_spec.rb",
     "test/rails/overrides/spec/controllers/emobile_spec.rb",
     "test/rails/overrides/app/controllers/trans_sid_controller.rb",
     "test/rails/overrides/app/controllers/template_path_controller.rb",
     "test/rails/overrides/app/controllers/filter_controller.rb",
     "test/rails/overrides/app/controllers/mobile_spec_controller.rb",
     "test/rails/overrides/app/controllers/docomo_guid_controller.rb",
     "test/rails/overrides/app/controllers/application_controller.rb",
     "test/rails/2.3.2/spec/controllers/trans_sid_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

